
modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/NovaMachina-Mods/ExNihiloSequentia-Mekanism/issues" #optional
[[mods]] #mandatory
modId="exnihilomekanism" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ex Nihilo: Sequentia - Mekanism Addon" #mandatory
updateJSONURL="https://raw.githubusercontent.com/NovaMachina-Mods/ExNihiloSequentia-Mekanism/1.16.X/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia-mekanism-addon/" #optional
logoFile="" #optional
credits="" #optional
authors="NovaMachina" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
An addon for Ex Nihilo: Sequentia that adds support for Mekanism.
'''
[[dependencies.exnihilomekanism]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihilomekanism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, )"
    ordering="NONE"
    side="BOTH"
[[dependencies.exnihilomekanism]]
    modId="exnihilosequentia"
    mandatory=true
    versionRange="[1.16-1.4.0.0, )"
    ordering="AFTER"
    side="BOTH"
[[dependencies.exnihilomekanism]]
    modId="mekanism"
    mandatory=true
    versionRange="[1.16.4-10.0.18.445, )"
    ordering="AFTER"
    side="BOTH"
